# frontend/Dockerfile.dev
FROM node:18-alpine

WORKDIR /app

# Installing dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copying source files
COPY . .

# Exposing port for development server
EXPOSE 3000

# Starting development server
CMD ["npm", "run", "dev"]
